security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  providers:
    in_memory:
      memory:
        users:
          user:
            password: user
            roles: 'ROLE_USER'
          admin:
            password: admin
            roles: 'ROLE_ADMIN'

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt|error)|css|images|js)/
      security: false

    main:
      pattern:   ^/api
      stateless: true
      anonymous: true
      provider: in_memory
      form_login:
        login_path: /api/login
        check_path: /api/login_check
        success_handler:          lexik_jwt_authentication.handler.authentication_success
        failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        require_previous_session: false
      lexik_jwt:
        authorization_header:
          enabled: true
          prefix: Bearer
        query_parameter:
          enabled: true
          name: bearer
        throw_exceptions: false
        create_entry_point: true
        authentication_provider: lexik_jwt_authentication.security.authentication.provider



  access_control:
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
